package com.jframe;

import com.resources.dao.DAOPartida;
import com.resources.dao.DAOUsuario;
import com.resources.prog.Baraja;
import com.resources.prog.Carta;
import com.resources.prog.Partida;
import com.resources.prog.Usuario;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Campos Delgado
 */
public class Juego extends javax.swing.JFrame {

    private Integer contadorApuestas;
    private List<JLabel> cartasPlayer;
    private List<JLabel> cartasPlayerF;
    private List<JLabel> cartasPlayerT;
    private List<Carta> manoPlayer;

    private List<JLabel> cartasJoker;
    private List<JLabel> cartasJokerF;
    private List<JLabel> cartasJokerT;

    private List<Carta> manoJoker;

    private List<JButton> descartes;

    private Usuario usuario;
    private MenuUser menu;
    private double bote;
    private Baraja baraja;

    public Juego(Usuario usuario, MenuUser menu) {
        this.menu = menu;
        this.usuario = usuario;

        contadorApuestas = 1;
        initComponents();
        setLocationRelativeTo(null);
        reintentar.setVisible(false);
        reintentar.setEnabled(false);
        titulo.setText(titulo.getText() + usuario.getName());

        baraja = new Baraja();
        baraja.barajar();

        //Jugador
        manoPlayer = baraja.repartirMano(5);
        cartasPlayer = new ArrayList();

        cartasPlayer.add(cartaP1);
        cartasPlayer.add(cartaP2);
        cartasPlayer.add(cartaP3);
        cartasPlayer.add(cartaP4);
        cartasPlayer.add(cartaP5);

        cartasPlayerF = new ArrayList();

        cartasPlayerF.add(cartaPF1);
        cartasPlayerF.add(cartaPF2);
        cartasPlayerF.add(cartaPF3);
        cartasPlayerF.add(cartaPF4);
        cartasPlayerF.add(cartaPF5);

        cartasPlayerT = new ArrayList();

        cartasPlayerT.add(cartaPT1);
        cartasPlayerT.add(cartaPT2);
        cartasPlayerT.add(cartaPT3);
        cartasPlayerT.add(cartaPT4);
        cartasPlayerT.add(cartaPT5);

        //Joker
        manoJoker = baraja.repartirMano(5);
        cartasJoker = new ArrayList();

        cartasJoker.add(cartaJ1);
        cartasJoker.add(cartaJ2);
        cartasJoker.add(cartaJ3);
        cartasJoker.add(cartaJ4);
        cartasJoker.add(cartaJ5);

        cartasJokerF = new ArrayList();

        cartasJokerF.add(cartaJF1);
        cartasJokerF.add(cartaJF2);
        cartasJokerF.add(cartaJF3);
        cartasJokerF.add(cartaJF4);
        cartasJokerF.add(cartaJF5);

        cartasJokerT = new ArrayList();

        cartasJokerT.add(cartaJT1);
        cartasJokerT.add(cartaJT2);
        cartasJokerT.add(cartaJT3);
        cartasJokerT.add(cartaJT4);
        cartasJokerT.add(cartaJT5);

        descartes = new ArrayList();

        descartes.add(descartarBoton1);
        descartes.add(descartarBoton2);
        descartes.add(descartarBoton3);
        descartes.add(descartarBoton4);

        for (int i = 0; i < manoPlayer.size(); i++) {
            cartasPlayer.get(i).setIcon(new ImageIcon(manoPlayer.get(i).getSprite()));
        }

        for (int i = 0; i < manoJoker.size(); i++) {
            cartasJoker.get(i).setIcon(new ImageIcon(manoJoker.get(i).getSprite()));
        }

        cartasPlayerF.stream().forEach(c -> c.setIcon(new ImageIcon(Carta.CardSpriteLoader.getFondoCarta())));
        cartasPlayerT.stream().forEach(c -> c.setIcon(new ImageIcon(Carta.CardSpriteLoader.getTopPlayer())));

        cartasJokerF.stream().forEach(c -> c.setIcon(new ImageIcon(Carta.CardSpriteLoader.getFondoCarta())));
        cartasJokerT.stream().forEach(c -> c.setIcon(new ImageIcon(Carta.CardSpriteLoader.getTopJoker())));

        fondoCartasP.setIcon(new ImageIcon(Carta.CardSpriteLoader.getFondoCartas()));

        for (int i = 0; i < 2; i++) {
            cartasPlayerT.get(i).setIcon(null);
        }

        if (usuario.getBalance() >= 10.00) {
            usuario.setBalance(usuario.getBalance() - 10.00);
            new DAOUsuario().setBalance(usuario);
            bote = 20.00;
        } else {
            bote = 0.00;
        }

        boteDouble.setText(bote + "");
        creditoDouble.setText(usuario.getBalance() + "");

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        cartaJ1 = new javax.swing.JLabel();
        rendirseBoton = new javax.swing.JButton();
        apostarBoton = new javax.swing.JButton();
        cartaP2 = new javax.swing.JLabel();
        cartaP3 = new javax.swing.JLabel();
        cartaP4 = new javax.swing.JLabel();
        cartaP5 = new javax.swing.JLabel();
        cartaJF1 = new javax.swing.JLabel();
        cartaPF2 = new javax.swing.JLabel();
        cartaPF3 = new javax.swing.JLabel();
        cartaPF4 = new javax.swing.JLabel();
        cartaPF5 = new javax.swing.JLabel();
        cartaJT1 = new javax.swing.JLabel();
        cartaPT2 = new javax.swing.JLabel();
        cartaPT3 = new javax.swing.JLabel();
        cartaPT4 = new javax.swing.JLabel();
        cartaPT5 = new javax.swing.JLabel();
        fondoCartasP = new javax.swing.JLabel();
        cartaP1 = new javax.swing.JLabel();
        cartaPF1 = new javax.swing.JLabel();
        cartaPT1 = new javax.swing.JLabel();
        cartaJT2 = new javax.swing.JLabel();
        cartaJT3 = new javax.swing.JLabel();
        cartaJT4 = new javax.swing.JLabel();
        cartaJT5 = new javax.swing.JLabel();
        cartaJ2 = new javax.swing.JLabel();
        cartaJ3 = new javax.swing.JLabel();
        cartaJ4 = new javax.swing.JLabel();
        cartaJ5 = new javax.swing.JLabel();
        cartaJF2 = new javax.swing.JLabel();
        cartaJF3 = new javax.swing.JLabel();
        cartaJF4 = new javax.swing.JLabel();
        cartaJF5 = new javax.swing.JLabel();
        boteLabel = new javax.swing.JLabel();
        boteDouble = new javax.swing.JLabel();
        creditoDouble = new javax.swing.JLabel();
        creditoLabel = new javax.swing.JLabel();
        salida = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        descartarBoton1 = new javax.swing.JButton();
        descartarBoton2 = new javax.swing.JButton();
        descartarBoton3 = new javax.swing.JButton();
        descartarBoton4 = new javax.swing.JButton();
        reintentar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JokerPoker");
        setUndecorated(true);
        setResizable(false);

        cartaJ1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaJ1, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJ1);
        cartaJ1.setBounds(40, 220, 142, 190);

        rendirseBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rendirseBoton.setText("Rendirse");
        rendirseBoton.setToolTipText("");
        rendirseBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendirseBotonActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(rendirseBoton, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(rendirseBoton);
        rendirseBoton.setBounds(10, 710, 378, 52);

        apostarBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apostarBoton.setText("Apostar");
        apostarBoton.setToolTipText("");
        apostarBoton.setActionCommand("¿No esta registrado? Pulse aquí");
        apostarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostarBotonActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(apostarBoton, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(apostarBoton);
        apostarBoton.setBounds(640, 710, 378, 52);

        cartaP2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaP2, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaP2);
        cartaP2.setBounds(200, 460, 142, 190);

        cartaP3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaP3, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaP3);
        cartaP3.setBounds(360, 460, 142, 190);

        cartaP4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaP4, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaP4);
        cartaP4.setBounds(520, 460, 142, 190);

        cartaP5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaP5, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaP5);
        cartaP5.setBounds(680, 460, 142, 190);
        jLayeredPane1.setLayer(cartaJF1, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJF1);
        cartaJF1.setBounds(40, 220, 142, 190);
        jLayeredPane1.setLayer(cartaPF2, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaPF2);
        cartaPF2.setBounds(200, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPF3, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaPF3);
        cartaPF3.setBounds(360, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPF4, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaPF4);
        cartaPF4.setBounds(520, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPF5, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaPF5);
        cartaPF5.setBounds(680, 460, 142, 190);
        jLayeredPane1.setLayer(cartaJT1, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaJT1);
        cartaJT1.setBounds(40, 220, 142, 190);
        jLayeredPane1.setLayer(cartaPT2, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaPT2);
        cartaPT2.setBounds(200, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPT3, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaPT3);
        cartaPT3.setBounds(360, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPT4, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaPT4);
        cartaPT4.setBounds(520, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPT5, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaPT5);
        cartaPT5.setBounds(680, 460, 142, 190);
        jLayeredPane1.setLayer(fondoCartasP, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(fondoCartasP);
        fondoCartasP.setBounds(-10, -10, 1050, 790);

        cartaP1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaP1, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaP1);
        cartaP1.setBounds(40, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPF1, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaPF1);
        cartaPF1.setBounds(40, 460, 142, 190);
        jLayeredPane1.setLayer(cartaPT1, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaPT1);
        cartaPT1.setBounds(40, 460, 142, 190);
        jLayeredPane1.setLayer(cartaJT2, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaJT2);
        cartaJT2.setBounds(200, 220, 142, 190);
        jLayeredPane1.setLayer(cartaJT3, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaJT3);
        cartaJT3.setBounds(360, 220, 142, 190);
        jLayeredPane1.setLayer(cartaJT4, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaJT4);
        cartaJT4.setBounds(520, 220, 142, 190);
        jLayeredPane1.setLayer(cartaJT5, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(cartaJT5);
        cartaJT5.setBounds(680, 220, 142, 190);
        jLayeredPane1.setLayer(cartaJ2, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJ2);
        cartaJ2.setBounds(200, 220, 142, 190);
        jLayeredPane1.setLayer(cartaJ3, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJ3);
        cartaJ3.setBounds(360, 220, 142, 190);
        jLayeredPane1.setLayer(cartaJ4, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJ4);
        cartaJ4.setBounds(520, 220, 142, 190);
        jLayeredPane1.setLayer(cartaJ5, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJ5);
        cartaJ5.setBounds(680, 220, 142, 190);

        cartaJF2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaJF2, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJF2);
        cartaJF2.setBounds(200, 220, 142, 190);

        cartaJF3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaJF3, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJF3);
        cartaJF3.setBounds(360, 220, 142, 190);

        cartaJF4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaJF4, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJF4);
        cartaJF4.setBounds(520, 220, 142, 190);

        cartaJF5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLayeredPane1.setLayer(cartaJF5, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(cartaJF5);
        cartaJF5.setBounds(680, 220, 142, 190);

        boteLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        boteLabel.setText("Bote");
        jLayeredPane1.setLayer(boteLabel, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(boteLabel);
        boteLabel.setBounds(880, 350, 90, 50);

        boteDouble.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        boteDouble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.setLayer(boteDouble, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(boteDouble);
        boteDouble.setBounds(840, 420, 180, 50);

        creditoDouble.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        creditoDouble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLayeredPane1.setLayer(creditoDouble, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(creditoDouble);
        creditoDouble.setBounds(400, 710, 230, 50);

        creditoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        creditoLabel.setText("Credito");
        jLayeredPane1.setLayer(creditoLabel, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(creditoLabel);
        creditoLabel.setBounds(450, 660, 130, 50);

        salida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        salida.setText("X");
        salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidaMouseClicked(evt);
            }
        });
        jLayeredPane1.setLayer(salida, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(salida);
        salida.setBounds(987, 10, 30, 40);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titulo.setText("Joker Poker  - ");
        jLayeredPane1.setLayer(titulo, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(titulo);
        titulo.setBounds(40, 20, 790, 80);

        descartarBoton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descartarBoton1.setText("Descartar");
        descartarBoton1.setToolTipText("");
        descartarBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBoton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(descartarBoton1, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(descartarBoton1);
        descartarBoton1.setBounds(60, 440, 90, 20);

        descartarBoton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descartarBoton2.setText("Descartar");
        descartarBoton2.setToolTipText("");
        descartarBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBoton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(descartarBoton2, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(descartarBoton2);
        descartarBoton2.setBounds(220, 440, 90, 20);

        descartarBoton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descartarBoton3.setText("Descartar");
        descartarBoton3.setToolTipText("");
        descartarBoton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBoton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(descartarBoton3, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(descartarBoton3);
        descartarBoton3.setBounds(380, 440, 90, 20);

        descartarBoton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descartarBoton4.setText("Descartar");
        descartarBoton4.setToolTipText("");
        descartarBoton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarBoton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(descartarBoton4, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(descartarBoton4);
        descartarBoton4.setBounds(540, 440, 90, 20);

        reintentar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        reintentar.setText("Reintentar");
        reintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reintentarActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(reintentar, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(reintentar);
        reintentar.setBounds(280, 140, 300, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rendirseBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendirseBotonActionPerformed
        if (contadorApuestas <= 4) {
            boteDouble.setText(0.0 + "");
            creditoDouble.setText(usuario.getBalance() + "");
            cartasPlayerT.stream().forEach(c -> c.setIcon(null));
            cartasJokerT.stream().forEach(c -> c.setIcon(null));
            apostarBoton.setEnabled(false);
            rendirseBoton.setEnabled(false);
            descartes.forEach(d -> d.setEnabled(false));
            reintentar.setVisible(true);
            reintentar.setEnabled(true);

            menu.estaActivo(true);
            pack();
        }

    }//GEN-LAST:event_rendirseBotonActionPerformed

    private void apostarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostarBotonActionPerformed
        if (contadorApuestas <= 4 && usuario.getBalance() >= 10.00) {
            usuario.setBalance(usuario.getBalance() - 10.00);
            new DAOUsuario().setBalance(usuario);
            bote += 20.00;

            boteDouble.setText(bote + "");
            creditoDouble.setText(usuario.getBalance() + "");
        }

        if (contadorApuestas < 4) {
            contadorApuestas++;
            cartasPlayerT.get(contadorApuestas).setIcon(null);
        }

        if (contadorApuestas == 4) {
            apostarBoton.setEnabled(false);
            rendirseBoton.setEnabled(false);
            contadorApuestas++;
            cartasJokerT.forEach(c -> c.setIcon(null));
            int cmp = Baraja.compararManos(manoPlayer, manoJoker);

            descartes.forEach(d -> d.setEnabled(false));
            reintentar.setVisible(true);
            reintentar.setEnabled(true);

            if (cmp < 0) {
                int valor = Baraja.evaluarMano(manoPlayer);
                JOptionPane.showMessageDialog(this, "Has ganado por " + Baraja.descripcionMano(valor), "Has ganado", JOptionPane.INFORMATION_MESSAGE);
                if (bote != 0.00) {
                    usuario.setBalance(usuario.getBalance() + bote);
                    new DAOUsuario().setBalance(usuario);

                    boteDouble.setText(0.0 + "");
                    creditoDouble.setText(usuario.getBalance() + "");
                }
            } else if (cmp > 0) {
                int valor = Baraja.evaluarMano(manoJoker);
                JOptionPane.showMessageDialog(this, "Has perdido por " + Baraja.descripcionMano(valor), "Has perdido", JOptionPane.INFORMATION_MESSAGE);
                if (bote != 0.00) {
                    boteDouble.setText(0.0 + "");
                    creditoDouble.setText(usuario.getBalance() + "");
                }
            } else {
                int valor = Baraja.evaluarMano(manoJoker);
                JOptionPane.showMessageDialog(this, "Empate por " + Baraja.descripcionMano(valor), "Empate", JOptionPane.INFORMATION_MESSAGE);
                if (bote != 0.00) {
                    usuario.setBalance(usuario.getBalance() + (bote / 2.0));

                    new DAOUsuario().setBalance(usuario);
                    boteDouble.setText(0.0 + "");
                    creditoDouble.setText(usuario.getBalance() + "");
                }
            }

            boolean gano = cmp < 0;

            DAOPartida daoP = new DAOPartida();
            Partida partida = new Partida((daoP.getMaxID() + 1), usuario, gano, Date.valueOf(LocalDate.now()));
            daoP.insertPartida(partida);

            menu.estaActivo(true);
        }

        pack();
    }//GEN-LAST:event_apostarBotonActionPerformed

    private void salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMouseClicked
        new DAOUsuario().setBalance(usuario);
        menu.estaActivo(true);
        dispose();
    }//GEN-LAST:event_salidaMouseClicked

    private void descartarBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBoton1ActionPerformed
        descarte(1);
    }//GEN-LAST:event_descartarBoton1ActionPerformed

    private void descartarBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBoton2ActionPerformed
        descarte(2);
    }//GEN-LAST:event_descartarBoton2ActionPerformed

    private void descartarBoton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBoton3ActionPerformed
        descarte(3);
    }//GEN-LAST:event_descartarBoton3ActionPerformed

    private void descartarBoton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarBoton4ActionPerformed
        descarte(4);
    }//GEN-LAST:event_descartarBoton4ActionPerformed

    private void reintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reintentarActionPerformed
        Juego nuevo = new Juego(usuario, menu);
        nuevo.setVisible(true);
        this.setVisible(false);

        dispose();
    }//GEN-LAST:event_reintentarActionPerformed

    private void descarte(int pos) {
        if (contadorApuestas >= (pos - 1)) {
            descartes.get(pos - 1).setEnabled(false);
            manoPlayer.set((pos - 1), baraja.repartir());
            cartasPlayer.get(pos - 1).setIcon(new ImageIcon(manoPlayer.get(pos - 1).getSprite()));

            if (usuario.getBalance() >= 10.00) {
                usuario.setBalance(usuario.getBalance() - 10.00);
                new DAOUsuario().setBalance(usuario);
                bote += 20.00;

                boteDouble.setText(bote + "");
                creditoDouble.setText(usuario.getBalance() + "");
            }

            repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apostarBoton;
    private javax.swing.JLabel boteDouble;
    private javax.swing.JLabel boteLabel;
    private javax.swing.JLabel cartaJ1;
    private javax.swing.JLabel cartaJ2;
    private javax.swing.JLabel cartaJ3;
    private javax.swing.JLabel cartaJ4;
    private javax.swing.JLabel cartaJ5;
    private javax.swing.JLabel cartaJF1;
    private javax.swing.JLabel cartaJF2;
    private javax.swing.JLabel cartaJF3;
    private javax.swing.JLabel cartaJF4;
    private javax.swing.JLabel cartaJF5;
    private javax.swing.JLabel cartaJT1;
    private javax.swing.JLabel cartaJT2;
    private javax.swing.JLabel cartaJT3;
    private javax.swing.JLabel cartaJT4;
    private javax.swing.JLabel cartaJT5;
    private javax.swing.JLabel cartaP1;
    private javax.swing.JLabel cartaP2;
    private javax.swing.JLabel cartaP3;
    private javax.swing.JLabel cartaP4;
    private javax.swing.JLabel cartaP5;
    private javax.swing.JLabel cartaPF1;
    private javax.swing.JLabel cartaPF2;
    private javax.swing.JLabel cartaPF3;
    private javax.swing.JLabel cartaPF4;
    private javax.swing.JLabel cartaPF5;
    private javax.swing.JLabel cartaPT1;
    private javax.swing.JLabel cartaPT2;
    private javax.swing.JLabel cartaPT3;
    private javax.swing.JLabel cartaPT4;
    private javax.swing.JLabel cartaPT5;
    private javax.swing.JLabel creditoDouble;
    private javax.swing.JLabel creditoLabel;
    private javax.swing.JButton descartarBoton1;
    private javax.swing.JButton descartarBoton2;
    private javax.swing.JButton descartarBoton3;
    private javax.swing.JButton descartarBoton4;
    private javax.swing.JLabel fondoCartasP;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton reintentar;
    private javax.swing.JButton rendirseBoton;
    private javax.swing.JLabel salida;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
