package com.jframe;

import com.resources.dao.DAOUsuario;
import com.resources.prog.Usuario;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Sergio Campos Delgado
 */
public class MenuUser extends javax.swing.JFrame {

    private Usuario usuario;
    private static BufferedImage fondoMenu;

    static {
        BufferedImage fondoMenu = null;
        try {
            fondoMenu = ImageIO.read(new File("fondoMenu.png"));
        } catch (IOException e) {
            System.out.println("MenuUser: ");
            e.printStackTrace();
        }
        MenuUser.fondoMenu = fondoMenu;
    }

    public MenuUser(Usuario usuario) {
        this.usuario = usuario;

        initComponents();
        setLocationRelativeTo(null);

        fondoMenuLabel.setIcon(new ImageIcon(MenuUser.getFondoMenu()));

        infoUserName.setText(
                usuario.getName()
        );

        infoCredito.setText(
                "Crédito:  " + usuario.getBalance()
        );

    }

    public static BufferedImage getFondoMenu() {
        return fondoMenu;
    }

    public void estaActivo(boolean estaActivo) {
        jugar.setEnabled(estaActivo);
        editarInfoUser.setEnabled(estaActivo);

        infoCredito.setText("Crédito:  " + usuario.getBalance());
        infoUserName.setText(usuario.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        fondoMenuLabel = new javax.swing.JLabel();
        salida = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jugar = new javax.swing.JButton();
        editarInfoUser = new javax.swing.JButton();
        infoUserName = new javax.swing.JLabel();
        infoCredito = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JokerPoker - Menu");
        setUndecorated(true);
        setResizable(false);

        jLayeredPane1.setLayer(fondoMenuLabel, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(fondoMenuLabel);
        fondoMenuLabel.setBounds(-10, -10, 1050, 790);

        salida.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        salida.setForeground(new java.awt.Color(204, 204, 204));
        salida.setText("X");
        salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidaMouseClicked(evt);
            }
        });
        jLayeredPane1.setLayer(salida, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(salida);
        salida.setBounds(987, 10, 30, 40);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(204, 204, 204));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Joker Poker  - Menu");
        jLayeredPane1.setLayer(titulo, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(titulo);
        titulo.setBounds(0, 100, 1020, 80);

        jugar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jugar.setText("Jugar");
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(jugar, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(jugar);
        jugar.setBounds(550, 340, 380, 30);

        editarInfoUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editarInfoUser.setText("Editar información");
        editarInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarInfoUserActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(editarInfoUser, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(editarInfoUser);
        editarInfoUser.setBounds(550, 420, 380, 30);

        infoUserName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        infoUserName.setForeground(new java.awt.Color(204, 204, 204));
        infoUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoUserName.setText("infoUserName");
        jLayeredPane1.setLayer(infoUserName, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(infoUserName);
        infoUserName.setBounds(0, 330, 550, 50);

        infoCredito.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        infoCredito.setForeground(new java.awt.Color(204, 204, 204));
        infoCredito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoCredito.setText("infoCredito");
        jLayeredPane1.setLayer(infoCredito, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane1.add(infoCredito);
        infoCredito.setBounds(0, 410, 550, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salidaMouseClicked

    private void editarInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarInfoUserActionPerformed
        //abre el menú de modinfouser
        ModInfoUser abrir = new ModInfoUser(usuario, this);
        abrir.setVisible(true);
        this.estaActivo(false);
    }//GEN-LAST:event_editarInfoUserActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        //abre el menú de juego
        Juego abrir = new Juego(usuario, this);
        abrir.setVisible(true);
        this.estaActivo(false);

    }//GEN-LAST:event_jugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser(new DAOUsuario().getUsuario("sergioscd")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarInfoUser;
    private javax.swing.JLabel fondoMenuLabel;
    private javax.swing.JLabel infoCredito;
    private javax.swing.JLabel infoUserName;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton jugar;
    private javax.swing.JLabel salida;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
