package com.jframe;

import com.resources.dao.DAOUsuario;
import com.resources.prog.Usuario;
import java.rmi.AccessException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Campos Delgado
 */
public class ModInfoAdmin extends javax.swing.JFrame {

    private static final List<Comparator<Usuario>> comparadores = List.of(
            new Usuario.ComparadorUserName(),
            new Usuario.ComparadorNombre(),
            new Usuario.ComparadorBalance()
    );
    private List<Usuario> listaUsuarios;
    private Usuario admin;
    private MenuAdmin menu;

    public ModInfoAdmin(Usuario admin, MenuAdmin menu) {
        if (admin.esAdmin()) {
            initComponents();
            cargarEventos();
            setLocationRelativeTo(null);
        } else {
            this.setEnabled(false);
            JOptionPane.showMessageDialog(dialogBalance, "EL USUARIO NO ES ADMINISTRADOR", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.admin = admin;
        this.menu = menu;
        cancelarDialogoBalance();

    }

    private void actualizarInfo() {
        new DAOUsuario().updateInfo(admin);
        menu.estaActivo(true);
        dispose();
    }

    public void cargarEventos() {
        listaUsuarios = new DAOUsuario().getUsuarios();
        DefaultListModel<Usuario> modeloListaEventos = new DefaultListModel();
        listaUsuarios.sort(null);
        modeloListaEventos.addAll(listaUsuarios);
        jListaUsuarios.setModel(modeloListaEventos);
    }

    public void OrdenarEventos(Comparator<Usuario> comparador) {
        DefaultListModel<Usuario> modeloListaEventos = new DefaultListModel();
        listaUsuarios.sort(comparador);
        modeloListaEventos.addAll(listaUsuarios);
        jListaUsuarios.setModel(modeloListaEventos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        dialogBalance = new javax.swing.JDialog();
        subit = new javax.swing.JButton();
        texto = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        tituloDialog = new javax.swing.JLabel();
        cabecera = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaUsuarios = new javax.swing.JList<>();
        setAdminUsuario = new javax.swing.JButton();
        editarCreditoUsuario = new javax.swing.JButton();
        registrarUsuario = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        ordenarLista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        JListaOrdenaciones = new javax.swing.JList<>();

        jScrollPane1.setViewportView(jEditorPane1);

        subit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subit.setText("Modificar");
        subit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subitActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        cancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        tituloDialog.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDialog.setText("MODIFICAR BALANCE");

        javax.swing.GroupLayout dialogBalanceLayout = new javax.swing.GroupLayout(dialogBalance.getContentPane());
        dialogBalance.getContentPane().setLayout(dialogBalanceLayout);
        dialogBalanceLayout.setHorizontalGroup(
            dialogBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogBalanceLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(texto)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogBalanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dialogBalanceLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cancelar)
                .addGap(55, 55, 55)
                .addComponent(subit)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        dialogBalanceLayout.setVerticalGroup(
            dialogBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogBalanceLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tituloDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(dialogBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(subit))
                .addGap(58, 58, 58))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JokerPoker - Modificar Info");
        setUndecorated(true);
        setResizable(false);

        cabecera.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        cabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cabecera.setText("Administracion de Usuarios");

        jListaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(jListaUsuarios);

        setAdminUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        setAdminUsuario.setText("Cambiar admin a Usuario");
        setAdminUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAdminUsuarioActionPerformed(evt);
            }
        });

        editarCreditoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editarCreditoUsuario.setText("Editar credito a Usuario");
        editarCreditoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCreditoUsuarioActionPerformed(evt);
            }
        });

        registrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registrarUsuario.setText("Registrar nuevo Usuario");
        registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarUsuarioActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        ordenarLista.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ordenarLista.setText("Ordenar");
        ordenarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarListaActionPerformed(evt);
            }
        });

        JListaOrdenaciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JListaOrdenaciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Nombre de Usuario", "Nombre", "Credito" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(JListaOrdenaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarCreditoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setAdminUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ordenarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cabecera)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarCreditoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(registrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setAdminUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ordenarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarCreditoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCreditoUsuarioActionPerformed
        if (jListaUsuarios.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Usuario", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            dialogBalance.pack();
            dialogBalance.setLocationRelativeTo(this);
            dialogBalance.setModal(true);
            dialogBalance.setVisible(true);
            texto.setText("");
        }
    }//GEN-LAST:event_editarCreditoUsuarioActionPerformed

    private void registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarUsuarioActionPerformed

    private void setAdminUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAdminUsuarioActionPerformed
        if (jListaUsuarios.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Usuario", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            Usuario u = jListaUsuarios.getSelectedValue();
            if (!u.getUserName().equals(admin.getUserName())) {
                u.setEsAdmin(!u.esAdmin());
                jListaUsuarios.repaint();
                new DAOUsuario().setAdmin(u);
            } else {
                JOptionPane.showMessageDialog(dialogBalance, "No se puede quitar admin a ti mismo", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_setAdminUsuarioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        menu.estaActivo(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void ordenarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarListaActionPerformed
        if (JListaOrdenaciones.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un Comparador", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            int valor = JListaOrdenaciones.getSelectedIndex();
            OrdenarEventos(comparadores.get(valor));
        }
    }//GEN-LAST:event_ordenarListaActionPerformed

    private void subitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subitActionPerformed
        try {
            double bal = Double.parseDouble(texto.getText());
            Usuario u = jListaUsuarios.getSelectedValue();
            u.setBalance(bal);
            new DAOUsuario().setBalance(u);
            jListaUsuarios.repaint();
            cancelarDialogoBalance();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(dialogBalance, "Debe poner un numero valido", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_subitActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        cancelarDialogoBalance();
    }//GEN-LAST:event_cancelarActionPerformed

    private void cancelarDialogoBalance() {
        dialogBalance.pack();
        dialogBalance.setLocationRelativeTo(this);
        dialogBalance.setModal(false);
        dialogBalance.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModInfoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModInfoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModInfoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModInfoAdmin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModInfoAdmin(new DAOUsuario().getUsuario("admin"), null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListaOrdenaciones;
    private javax.swing.JLabel cabecera;
    private javax.swing.JButton cancelar;
    private javax.swing.JDialog dialogBalance;
    private javax.swing.JButton editarCreditoUsuario;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JList<Usuario> jListaUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton ordenarLista;
    private javax.swing.JButton registrarUsuario;
    private javax.swing.JButton salir;
    private javax.swing.JButton setAdminUsuario;
    private javax.swing.JButton subit;
    private javax.swing.JTextField texto;
    private javax.swing.JLabel tituloDialog;
    // End of variables declaration//GEN-END:variables
}
